# Generated by Django 4.0.5 on 2022-07-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.CharField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='data',
            name='country',
            field=models.CharField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='data',
            name='end_year',
            field=models.CharField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='data',
            name='impact',
            field=models.CharField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='data',
            name='insight',
            field=models.CharField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='data',
            name='pestle',
            field=models.CharField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.CharField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='data',
            name='region',
            field=models.CharField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='data',
            name='sector',
            field=models.CharField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.CharField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(blank=True, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='data',
            name='topic',
            field=models.CharField(blank=True, max_length=100000000),
        ),
    ]
