# Generated by Django 4.0.5 on 2022-07-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_data_added_alter_data_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='added',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='country',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='end_year',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='impact',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='insight',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='pestle',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='region',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='sector',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='start_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='topic',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
